# Project: Tema_POO_Arduino_Detector_gaz
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = buzzer.o led.o motor.o senzor_gaz.o
LINKOBJ  = buzzer.o led.o motor.o senzor_gaz.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Tema_POO_Arduino_Detector_gaz.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

buzzer.o: buzzer.cpp
	$(CPP) -c buzzer.cpp -o buzzer.o $(CXXFLAGS)

led.o: led.cpp
	$(CPP) -c led.cpp -o led.o $(CXXFLAGS)

motor.o: motor.cpp
	$(CPP) -c motor.cpp -o motor.o $(CXXFLAGS)

senzor_gaz.o: senzor_gaz.cpp
	$(CPP) -c senzor_gaz.cpp -o senzor_gaz.o $(CXXFLAGS)
